### ISSUE TITLE
Now Playing crashes

### ISSUE THREAD

**Issue by amogus07** [KieronQuinn/AmbientMusicMod#152]
Pocophone F1, Android 13 QPR, Magisk Delta

Downloading the database finally worked, but now I often get these errors: 

```
FATAL EXCEPTION: main
Process: com.kieronquinn.app.pixelambientmusic, PID: 6507
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in fpx@48a47c0
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
	at android.provider.DeviceConfig.enforceReadPermission(DeviceConfig.java:1212)
	at android.provider.Settings$NameValueCache.getStringsForPrefix(Settings.java:3301)
	at android.provider.Settings$Config.getStrings(Settings.java:18589)
	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:811)
	at android.provider.DeviceConfig.getProperty(DeviceConfig.java:783)
	at android.provider.DeviceConfig.getInt(DeviceConfig.java:863)
	at jvu.a(Unknown Source:5)
	at etq.i(PG:9)
	at etq.c(PG:2)
	at dwx.e(PG:3)
	at dwx.d(Unknown Source:10)
	at dwp.d(Unknown Source:22)
	at doq.d(Unknown Source:9)
	at dnt.f(PG:2)
	at bva.aC(PG:24)
	at bvh.g(PG:70)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:72)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:73)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:75)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:76)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:79)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:80)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bva.aQ(Unknown Source:59)
	at bvh.b(PG:107)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bva.aP(Unknown Source:2)
	at bvh.b(PG:109)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bvh.b(PG:115)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bvh.b(PG:116)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at fpx.onReceive(PG:35)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 9 more
```
```
Tracking association SourceState{3d7cfe2 com.kieronquinn.app.ambientmusicmod/10427 BTopFgs #5822} whose proc state 2 is better than process ProcessState{d9381c8 com.kieronquinn.app.pixelambientmusic/10430 pkg=com.kieronquinn.app.pixelambientmusic} proc state 3 (1266 skipped)
```
```
[6507,0,com.kieronquinn.app.pixelambientmusic,818462278,java.lang.SecurityException,Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG,DeviceConfig.java,1212]
```
I have seen that there was a similar issue on another device, but I would really like to get it to work, so please tell me if there's anything I can try

**Comment by KieronQuinn** [comment]
I already commented on the cause of this in #146, nothing else can be done.

**Comment by amogus07** [comment]
Is there any way to fix the permission denial from the rom side?

**Comment by amogus07** [comment]
or, could adding the permission in AndroidManifest.xml help? I tried modifying it with NP Manager but it caused both Now Playing and Ambient Music Mod to keep crashing, probably because of a signature mismatch

**Comment by KieronQuinn** [comment]
It's a priv-app permission, and the signatures have to match. Neither of those can be achieved by Ambient Music Mod.

The hooking already effectively removes the code which is causing the crash. If hooking is not working, then I cannot do anything else.
