### ISSUE TITLE
Now Playing crushing If I click on a search result in history!!!

### ISSUE THREAD

**Issue by Arafat0010** [KieronQuinn/AmbientMusicMod#182]
`When` I try to open the songs details from now playing history It crushes.

<details><summary>Details</summary>
<p>

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/WindowInsetsAnimation$Callback;
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at so.<init>(PG:21)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(PG:2)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at android.view.View.inflate(View.java:26090)
	at nen.g(PG:1)
	at nen.f(PG:1)
	at nen.setContentView(PG:2)
	at p.a(PG:4)
	at ads.i(PG:4)
	at ads.c(PG:2)
	at adt.h(PG:3)
	at z.m(PG:6)
	at r.m(PG:1)
	at ba.b(PG:16)
	at ba.d(PG:159)
	at au.am(PG:60)
	at au.an(PG:8)
	at au.ad(PG:7)
	at an.run(PG:72)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: android.view.WindowInsetsAnimation$Callback
	... 34 more

</p>
</details> 

![Screenshot_2023-05-28-10-50-26-333_com kieronquinn app ambientmusicmod](https://github.com/KieronQuinn/AmbientMusicMod/assets/134326236/56aed0e2-99da-4cec-88a0-cf3af1c93530)

**Comment by Mainak009** [comment]
Mine is also happening same, so not creating another issue and attaching my crash log here

Log 1: https://bin.kv2.dev/~64f774ea5de7ed6bfdb90794
Log 2: https://bin.kv2.dev/~64f775bb5de7ed6bfdb90796
Device: Redmi Note 10
ROM: PixelOS Android 13

![Screenshot_20230906-001932.png](https://github.com/KieronQuinn/AmbientMusicMod/assets/52679017/61c29134-ef6a-4d57-81aa-f8c765578c3a)

**Comment by KieronQuinn** [comment]
> Mine is also happening same, so not creating another issue and attaching my crash log here
> 
> Log 1: https://bin.kv2.dev/~64f774ea5de7ed6bfdb90794 Log 2: https://bin.kv2.dev/~64f775bb5de7ed6bfdb90796 Device: Redmi Note 10 ROM: PixelOS Android 13
> 
> ![Screenshot_20230906-001932.png](https://user-images.githubusercontent.com/52679017/265798561-61c29134-ef6a-4d57-81aa-f8c765578c3a.png)

Yours is #146, not related to this issue.

**Comment by Mainak009** [comment]
> > Mine is also happening same, so not creating another issue and attaching my crash log here
> > 
> > Log 1: https://bin.kv2.dev/~64f774ea5de7ed6bfdb90794 Log 2: https://bin.kv2.dev/~64f775bb5de7ed6bfdb90796 Device: Redmi Note 10 ROM: PixelOS Android 13
> > 
> 
> Yours is #146, not related to this issue. 

Wow so this issue is unfixable🥲😪

**Comment by KieronQuinn** [comment]
> > > Mine is also happening same, so not creating another issue and attaching my crash log here
> > > Log 1: https://bin.kv2.dev/~64f774ea5de7ed6bfdb90794 Log 2: https://bin.kv2.dev/~64f775bb5de7ed6bfdb90796 Device: Redmi Note 10 ROM: PixelOS Android 13
> > 
> > 
> > Yours is #146, not related to this issue.
> 
> Wow so this issue is unfixable🥲😪

It's not in scope of this app.

**Comment by KieronQuinn** [comment]
Fixed in Now Playing 1.3.2
