### ISSUE TITLE
Now playing crashing

### ISSUE THREAD

**Issue by mchyla7** [KieronQuinn/AmbientMusicMod#196]
Now playing crashing because he miss some permissions?
Android 13
AmbientMusicMod - 2.3.1
NowPlaying - 1.3.1
Android system intelligence - T.30.playstore.pixel5.546346341

Error:
`time: 1692341682147
msg: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
stacktrace: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 } in frb@26da660
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7927)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
	at android.provider.DeviceConfig.enforceReadPermission(DeviceConfig.java:1219)
	at android.provider.Settings$NameValueCache.getStringsForPrefix(Settings.java:3286)
	at android.provider.Settings$Config.getStrings(Settings.java:18355)
	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:818)
	at android.provider.DeviceConfig.getProperty(DeviceConfig.java:790)
	at android.provider.DeviceConfig.getInt(DeviceConfig.java:870)
	at jtj.a(Unknown Source:5)
	at etb.i(PG:9)
	at etb.c(PG:2)
	at dvv.e(PG:2)
	at dvv.d(Unknown Source:10)
	at dvm.e(Unknown Source:22)
	at dnq.e(Unknown Source:9)
	at dnd.e(PG:2)
	at bun.cq(PG:24)
	at buv.h(PG:35)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:36)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:37)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:39)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:40)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:41)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at buv.h(PG:42)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at bun.aD(Unknown Source:70)
	at buv.b(PG:103)
	at buv.a(PG:276)
	at rlk.a(PG:1)
	at bun.aC(Unknown Source:2)
	at buv.b(PG:105)
	at buv.a(PG:276)
	at rlk.a(PG:1)
	at buv.b(PG:111)
	at buv.a(PG:276)
	at rlk.a(PG:1)
	at rlj.a(PG:2)
	at buv.h(PG:47)
	at buv.a(PG:274)
	at rlk.a(PG:1)
	at frb.onReceive(PG:19)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 9 more
`

**Comment by KieronQuinn** [comment]
#146
