### ISSUE TITLE
OnDemand Recognition doesn't seem to work, Fatal Exception in logcat.

### ISSUE THREAD

**Issue by poob1** [KieronQuinn/AmbientMusicMod#232]
I've already installed the correct Google App variant with the split_fingerprint sound splitapk, local recognition works fine, but OnDemand just gets stuck while on the recognition animation and my logcat says the following things:

```
02-25 13:06:04.713  6959  6959 E AndroidRuntime: FATAL EXCEPTION: main
02-25 13:06:04.713  6959  6959 E AndroidRuntime: PID: 6959
02-25 13:06:04.713  6959  6959 E AndroidRuntime: java.lang.NoSuchMethodException: android.content.Context.getServiceDispatcher [interface android.content.ServiceConnection, class android.os.Handler, int]
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2937)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2449)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.utils.extensions.Extensions_ContextKt.getServiceDispatcher(Extensions+Context.kt:134)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invokeSuspend(Extensions+Coroutines.kt:41)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:8)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:4)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.getMusicRecognitionService(RootMusicRecognitionManager.kt:404)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.runStreamingSearch(RootMusicRecognitionManager.kt:95)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.service.ShizukuService$beginStreamingSearchViaRoot$1$1.invokeSuspend(ShizukuService.kt:350)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:222)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:314)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at moe.shizuku.starter.ServiceStarter.main(SourceFile:43)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
02-25 13:06:04.713  6959  6959 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@83fad69, Dispatchers.Main]
02-25 13:06:51.705  9357  9357 E AndroidRuntime: FATAL EXCEPTION: main
02-25 13:06:51.705  9357  9357 E AndroidRuntime: PID: 9357
02-25 13:06:51.705  9357  9357 E AndroidRuntime: java.lang.NoSuchMethodException: android.content.Context.getServiceDispatcher [interface android.content.ServiceConnection, class android.os.Handler, int]
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2937)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2449)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.utils.extensions.Extensions_ContextKt.getServiceDispatcher(Extensions+Context.kt:134)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invokeSuspend(Extensions+Coroutines.kt:41)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:8)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:4)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.getMusicRecognitionService(RootMusicRecognitionManager.kt:404)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.runStreamingSearch(RootMusicRecognitionManager.kt:95)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.service.ShizukuService$beginStreamingSearchViaRoot$1$1.invokeSuspend(ShizukuService.kt:350)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:222)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:314)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at moe.shizuku.starter.ServiceStarter.main(SourceFile:43)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
02-25 13:06:51.705  9357  9357 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6cd7c, Dispatchers.Main]
02-25 13:15:03.551 17064 17064 E AndroidRuntime: FATAL EXCEPTION: main
02-25 13:15:03.551 17064 17064 E AndroidRuntime: PID: 17064
02-25 13:15:03.551 17064 17064 E AndroidRuntime: java.lang.NoSuchMethodException: android.content.Context.getServiceDispatcher [interface android.content.ServiceConnection, class android.os.Handler, int]
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2937)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2449)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.utils.extensions.Extensions_ContextKt.getServiceDispatcher(Extensions+Context.kt:134)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invokeSuspend(Extensions+Coroutines.kt:41)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:8)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager$getMusicRecognitionService$lambda$2$$inlined$suspendCancellableCoroutineWithTimeout$1.invoke(Unknown Source:4)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.getMusicRecognitionService(RootMusicRecognitionManager.kt:404)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.components.musicrecognition.RootMusicRecognitionManager.runStreamingSearch(RootMusicRecognitionManager.kt:95)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.kieronquinn.app.ambientmusicmod.service.ShizukuService$beginStreamingSearchViaRoot$1$1.invokeSuspend(ShizukuService.kt:350)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:222)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:314)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at moe.shizuku.starter.ServiceStarter.main(SourceFile:43)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
02-25 13:15:03.551 17064 17064 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d3ca306, Dispatchers.Main]
```

I will also attach the logcat itself as a file.
[ambientest.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/14396158/ambientest.txt)

Things I think are worth mentioning:

I'm on HyperOS Android 14.
I am rooted with Magisk.

**Comment by KieronQuinn** [comment]
Fixed in 2.3.4
