### ISSUE TITLE
Sometimes the "now playing history" shortcut and probably also the recognition stops

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/AmbientMusicMod#34]
I assume that this might not only affect the shortcut but that's the only place where I noticed it, sometimes the shortcut for the now playing history stops working, and using Scoop I recorded the crash log and hope you can find any use in it

FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.google.intelligence.sense, PID: 24499
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9392)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1757)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.widget.AbsListView.requestLayout(AbsListView.java:2034)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.view.View.requestLayout(View.java:25595)
	at android.widget.ImageView.setImageDrawable(ImageView.java:605)
	at com.kieronquinn.app.ambientmusicmod.xposed.apps.PixelAmbientServices$setAlbumArtImage$1.invokeSuspend(PixelAmbientServices.kt:477)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by KieronQuinn** [comment]
Seems to happen when the song doesn't have a YTM option (which is rare). If it persists, disable the album art option in the Ambient Music Mod settings.

**Comment by MKCOOL142** [comment]
Do I need the YouTube music app for it to display the option or are you talking about if the song even exists on youtube music at all? Also disabling the cover did fix it
